### ISSUE TITLE
initialSelections does not show when recurring

### ISSUE THREAD

**Issue by causztic** [trotzig/react-available-times#7]
I tried setting recurring to true and added in these values for `initialSelections`:

```javascript
[{
        start: new Date(2018, 0, 1, 1, 0),
        end: new Date(2018, 0, 2, 2, 0),
}]
```
It works when it is not recurring (the values appear on the calendar and can be modified) but it does not show up otherwise. Any ideas?

**Comment by trotzig** [comment]
I believe the dates need to be in the current week, otherwise they won't show up in the recurring view (this is from memory, I haven't double-checked).

**Comment by causztic** [comment]
Just tried setting it to be current week ```new Date(2018, 2, 27, 8, 0)``` and it doesn't work either. I will try to investigate it

**Comment by trotzig** [comment]
Okay, I know what's wrong. Sorry for the confusion around dates needing to be in the current week, that's not the case. Recurring time slots are expressed as the number of minutes from the start of the week (either 00:00 on Sunday or 00:00 on Monday depending on the `weekStartsOn` prop). So in order to pass `initialSelections` when in `recurring` mode, you have to pass something like: 

```js
[{
        start: 1000,
        end: 1100,
}]
```

This isn't really documented well. There's a section around `recurring` in the Props block, but nothing about `initialSelections`. https://github.com/trotzig/react-available-times#props

**Comment by causztic** [comment]
Thanks! That clears things up 👍
